FROM python:alpine

LABEL NAME="PDFusion"

LABEL MAJORVERSION=1

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /PDFusion

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN apt update && apt install -y ghostscript && rm -rf /var/lib/apt/lists/*

COPY ./src ./src

CMD ["python", "./src/fusionHA.py"]