FROM python

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /PDFusion

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN apt update && apt install -y poppler-utils && rm -rf /var/lib/apt/lists/*

COPY ./src ./src

CMD ["python", "./src/fusionHA.py"]