FROM python:alpine

LABEL NAME="PDFusion"

LABEL MAJORVERSION=1

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /PDFusion

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN apk add --update-cache ghostscript && rm -rf /var/cache/apk/*

COPY ./src ./src

CMD ["python", "./src/fusionHA.py"]